"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { COLLECTIONS, COLLECTION_SLUGS, CollectionSlug } from "@/lib/types";

type Row=any;
const blank={title:"",slug:"",publish_date:new Date().toISOString(),featured:false,draft:true,category:"",tags:[],genre:[],mood:[],language:[],month:"",year:new Date().getFullYear(),cover_image:"",cover_image_alt:"",excerpt:"",author:"",display_order:null,artist_name:"",artist_image:"",location:"",country:"",artist_links:{},curator:"",spotify_url:"",apple_music_url:"",youtube_url:"",week_label:"",research_notes:"",tracks:[],body:"",seo_title:"",seo_description:"",seo_image:"",canonical_url:""};

export default function AdminCollection(){
 const {collection}=useParams<{collection:string}>(); const router=useRouter(); const valid=COLLECTION_SLUGS.includes(collection as CollectionSlug); const meta=valid?COLLECTIONS[collection as CollectionSlug]:null;
 const [rows,setRows]=useState<Row[]>([]); const [editing,setEditing]=useState<Row|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 async function load(){setLoading(true);const r=await fetch(`/api/admin/content?collection=${collection}`);if(r.status===401){router.push('/admin/login');return;}setRows(await r.json());setLoading(false)}
 useEffect(()=>{if(valid)load()},[collection]);
 const isSpotlight=meta?.isSpotlight; const hasTracks=meta?.hasTracks;
 if(!meta)return <main className="p-10">Unknown collection.</main>;
 async function save(){if(!editing)return;setSaving(true);setMessage("");const payload={...editing,collection,slug:editing.slug||editing.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')};let r;if(editing.id)r=await fetch(`/api/admin/content/${editing.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});else r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)setMessage(d.error||'Could not save');else{setMessage('Saved.');setEditing(d);load()}setSaving(false)}
 async function remove(id:string){if(!confirm('Delete this content permanently?'))return;const r=await fetch(`/api/admin/content/${id}`,{method:'DELETE'});if(r.ok)load();}
 async function upload(file:File){const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});const d=await r.json();if(r.ok)setEditing((x:any)=>({...x,cover_image:d.url}));else setMessage(d.error||'Upload failed')}
 return <main className="min-h-screen bg-neutral-50 dark:bg-[#0a0a0c]"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/admin" className="text-xs text-neutral-500">← Dashboard</Link><h1 className="mt-1 font-display text-3xl font-black">{meta.label}</h1></div><button onClick={()=>setEditing({...blank})} className="rounded-xl bg-black px-5 py-3 text-sm font-bold text-white dark:bg-white dark:text-black">+ Add {meta.singularLabel}</button></div>
 <div className="mt-8 grid gap-3">{loading?<p className="text-sm text-neutral-500">Loading…</p>:rows.length===0?<p className="rounded-2xl border border-dashed p-8 text-center text-sm text-neutral-500">No content yet. Add your first {meta.singularLabel.toLowerCase()}.</p>:rows.map(r=><div key={r.id} className="flex items-center justify-between gap-4 rounded-2xl border border-black/10 bg-white p-4 dark:border-white/10 dark:bg-white/[.04]"><div className="min-w-0"><p className="truncate font-semibold">{r.title}</p><p className="mt-1 text-xs text-neutral-500">{r.draft?'Draft':'Published'} · {r.slug}</p></div><div className="flex gap-2"><button onClick={()=>setEditing(r)} className="rounded-lg border px-3 py-2 text-xs">Edit</button><button onClick={()=>remove(r.id)} className="rounded-lg border px-3 py-2 text-xs text-red-600">Delete</button></div></div>)}</div>
 {editing&&<Editor value={editing} setValue={setEditing} onSave={save} onCancel={()=>setEditing(null)} onUpload={upload} saving={saving} message={message} isSpotlight={!!isSpotlight} hasTracks={!!hasTracks}/>}</div></main>
}

function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="block text-sm font-semibold">{label}<div className="mt-1.5">{children}</div></label>}
function Input(p:any){return <input {...p} className="admin-input"/>}
function Textarea(p:any){return <textarea {...p} className="admin-input min-h-28"/>}
function Editor({value,setValue,onSave,onCancel,onUpload,saving,message,isSpotlight,hasTracks}:{value:any,setValue:any,onSave:()=>void,onCancel:()=>void,onUpload:(f:File)=>void,saving:boolean,message:string,isSpotlight:boolean,hasTracks:boolean}){
 const set=(k:string,v:any)=>setValue((x:any)=>({...x,[k]:v})); const arr=(k:string)=>Array.isArray(value[k])?value[k].join(', '):'';
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/40 p-4"><div className="mx-auto my-8 max-w-4xl rounded-3xl bg-white p-6 shadow-2xl dark:bg-[#111114] sm:p-8"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-black">{value.id?'Edit':'Add'} Content</h2><button onClick={onCancel}>✕</button></div>
 <div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Title"><Input value={value.title} onChange={(e:any)=>set('title',e.target.value)}/></Field><Field label="Slug"><Input value={value.slug} onChange={(e:any)=>set('slug',e.target.value)}/></Field><Field label="Category"><Input value={value.category} onChange={(e:any)=>set('category',e.target.value)}/></Field><Field label="Author"><Input value={value.author||''} onChange={(e:any)=>set('author',e.target.value)}/></Field><Field label="Publish date"><Input type="datetime-local" value={value.publish_date?new Date(value.publish_date).toISOString().slice(0,16):''} onChange={(e:any)=>set('publish_date',new Date(e.target.value).toISOString())}/></Field><Field label="Year"><Input type="number" value={value.year||''} onChange={(e:any)=>set('year',e.target.value?Number(e.target.value):null)}/></Field><Field label="Tags (comma separated)"><Input value={arr('tags')} onChange={(e:any)=>set('tags',e.target.value.split(',').map((x:string)=>x.trim()).filter(Boolean))}/></Field><Field label="Genres (comma separated)"><Input value={arr('genre')} onChange={(e:any)=>set('genre',e.target.value.split(',').map((x:string)=>x.trim()).filter(Boolean))}/></Field><Field label="Excerpt"><Textarea value={value.excerpt} onChange={(e:any)=>set('excerpt',e.target.value)}/></Field><Field label="Cover image"><div className="flex gap-2"><Input value={value.cover_image} onChange={(e:any)=>set('cover_image',e.target.value)}/><label className="shrink-0 cursor-pointer rounded-xl border px-3 py-2 text-xs"><input type="file" accept="image/*" className="hidden" onChange={(e:any)=>e.target.files?.[0]&&onUpload(e.target.files[0])}/>Upload</label></div></Field>{isSpotlight&&<>
 <Field label="Artist name"><Input value={value.artist_name||''} onChange={(e:any)=>set('artist_name',e.target.value)}/></Field>
 <Field label="Artist image"><Input value={value.artist_image||''} onChange={(e:any)=>set('artist_image',e.target.value)}/></Field>
 <Field label="Location"><Input value={value.location||''} onChange={(e:any)=>set('location',e.target.value)}/></Field>
 <Field label="Spotify link"><Input type="url" placeholder="https://open.spotify.com/..." value={value.artist_links?.spotify||''} onChange={(e:any)=>set('artist_links',{...(value.artist_links||{}),spotify:e.target.value})}/></Field>
 <Field label="Apple Music link"><Input type="url" placeholder="https://music.apple.com/..." value={value.artist_links?.appleMusic||''} onChange={(e:any)=>set('artist_links',{...(value.artist_links||{}),appleMusic:e.target.value})}/></Field>
 <Field label="Amazon Music link"><Input type="url" placeholder="https://music.amazon.in/..." value={value.artist_links?.amazonMusic||''} onChange={(e:any)=>set('artist_links',{...(value.artist_links||{}),amazonMusic:e.target.value})}/></Field>
 <Field label="YouTube link"><Input type="url" placeholder="https://youtube.com/..." value={value.artist_links?.youtube||''} onChange={(e:any)=>set('artist_links',{...(value.artist_links||{}),youtube:e.target.value})}/></Field>
 </>}
 <div className="sm:col-span-2"><Field label="Article / editorial content (Markdown supported)"><Textarea className="min-h-[360px]" value={value.body} onChange={(e:any)=>set('body',e.target.value)}/></Field></div>
 {hasTracks&&<div className="sm:col-span-2"><Field label="Tracks (JSON, optional)"><Textarea value={JSON.stringify(value.tracks||[],null,2)} onChange={(e:any)=>{try{set('tracks',JSON.parse(e.target.value))}catch{}}}/></Field></div>}
 <div className="sm:col-span-2 grid gap-3 rounded-2xl border p-4 sm:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!value.featured} onChange={e=>set('featured',e.target.checked)}/> Featured</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!value.draft} onChange={e=>set('draft',e.target.checked)}/> Draft (hidden from public site)</label></div>
 </div><div className="mt-6 flex items-center justify-between"><span className="text-sm text-neutral-500">{message}</span><div className="flex gap-2"><button onClick={onCancel} className="rounded-xl border px-5 py-3 text-sm">Cancel</button><button disabled={saving} onClick={onSave} className="rounded-xl bg-black px-5 py-3 text-sm font-bold text-white disabled:opacity-50 dark:bg-white dark:text-black">{saving?'Saving…':'Save'}</button></div></div></div></div>
}
