"use client";

import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, ArrowUp, ArrowDown, ImagePlus, Trash2 } from "lucide-react";
import { COLLECTIONS } from "@/lib/types";

const EDITORIAL = ["articles", "artist-spotlights", "trend-reports", "playlists"] as const;
type EditorialCollection = typeof EDITORIAL[number];
type Row = any;
const blank = { title:"",slug:"",publish_date:new Date().toISOString(),featured:false,draft:true,category:"",tags:[],genre:[],language:[],month:"",year:new Date().getFullYear(),cover_image:"",cover_image_alt:"",excerpt:"",author:"",display_order:null,artist_name:"",artist_image:"",location:"",country:"",artist_links:{},curator:"",spotify_url:"",apple_music_url:"",youtube_url:"",research_notes:"",tracks:[],body:"",seo_title:"",seo_description:"",seo_image:"",canonical_url:"" };

export default function AdminCollection(){
  const {collection}=useParams<{collection:string}>();const router=useRouter();const valid=EDITORIAL.includes(collection as EditorialCollection);const meta=valid?COLLECTIONS[collection as EditorialCollection]:null;const [rows,setRows]=useState<Row[]>([]);const [editing,setEditing]=useState<Row|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
  async function load(){setLoading(true);const response=await fetch(`/api/admin/content?collection=${collection}`);if(response.status===401){router.push("/admin/login");return;}setRows(await response.json());setLoading(false);}
  useEffect(()=>{if(valid)load();},[collection,valid]);
  if(!meta)return <main className="p-10">Unknown editorial section.</main>;
  async function save(){if(!editing)return;setSaving(true);setMessage("");const payload={...editing,collection,slug:editing.slug||editing.title.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")};const response=editing.id?await fetch(`/api/admin/content/${editing.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}):await fetch("/api/admin/content",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)setMessage(data.error||"Could not save.");else{setMessage("Saved.");setEditing(data);await load();}setSaving(false);}
  async function remove(id:string){if(!confirm("Delete this content permanently? This cannot be undone."))return;const response=await fetch(`/api/admin/content/${id}`,{method:"DELETE"});if(response.ok)load();}
  async function upload(file:File){const form=new FormData();form.append("file",file);const response=await fetch("/api/admin/upload",{method:"POST",body:form});const data=await response.json();if(response.ok)setEditing((x:Row)=>({...x,cover_image:data.url}));else setMessage(data.error||"Upload failed.");}
  const isArtist=collection==="artist-spotlights";const isPlaylist=collection==="playlists";
  return <main className="min-h-screen bg-[#f4f1ea] dark:bg-[#0a0a0c]"><div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 sm:py-12">
    <header className="flex flex-wrap items-end justify-between gap-5 border-b border-black/10 pb-7 dark:border-white/10"><div><Link href="/admin" className="inline-flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.15em] text-neutral-400 hover:text-accent"><ArrowLeft size={13}/> Editorial Desk</Link><p className="mt-5 editorial-kicker">Content manager</p><h1 className="mt-2 font-display text-5xl font-black uppercase leading-none tracking-[-.05em]">{isArtist?"Artist Spotlights":meta.label}</h1></div><button onClick={()=>setEditing({...blank})} className="bg-black px-5 py-3 text-xs font-bold uppercase tracking-[.12em] text-white dark:bg-white dark:text-black">+ New {isArtist?"Artist":meta.singularLabel}</button></header>
    <div className="mt-6 flex items-center justify-between"><p className="editorial-meta">{rows.length} entries · {rows.filter(r=>!r.draft).length} published · {rows.filter(r=>r.draft).length} drafts</p></div>
    <div className="mt-3 border-t border-black/10 dark:border-white/10">{loading?<p className="py-10 text-sm text-neutral-500">Loading…</p>:rows.length===0?<p className="py-16 text-center text-sm text-neutral-500">No entries yet. Create the first one.</p>:rows.map((row)=><div key={row.id} className="grid gap-4 border-b border-black/10 py-4 sm:grid-cols-[72px_1fr_auto] sm:items-center dark:border-white/10"><div className="relative aspect-[4/3] overflow-hidden bg-neutral-200 dark:bg-neutral-800">{row.cover_image&&<img src={row.cover_image} alt="" className="h-full w-full object-cover"/>}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="editorial-kicker">{row.category||meta.singularLabel}</span>{row.featured&&<span className="bg-accent/10 px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-accent">Featured</span>}<span className="text-[9px] uppercase tracking-wider text-neutral-400">{row.draft?"Draft":"Published"}</span></div><p className="mt-1 truncate font-display text-xl font-black">{row.title}</p><p className="mt-1 truncate text-xs text-neutral-400">{row.slug}</p></div><div className="flex gap-2 sm:justify-end"><button onClick={()=>setEditing(row)} className="border border-black/10 px-3 py-2 text-[10px] font-bold uppercase tracking-wider hover:border-accent dark:border-white/15">Edit</button><button onClick={()=>remove(row.id)} aria-label={`Delete ${row.title}`} className="border border-red-500/30 px-3 py-2 text-red-600 hover:bg-red-50 dark:hover:bg-red-950/20"><Trash2 size={14}/></button></div></div>)}</div>
    {editing&&<Editor value={editing} setValue={setEditing} onSave={save} onCancel={()=>setEditing(null)} onUpload={upload} saving={saving} message={message} isArtist={isArtist} isPlaylist={isPlaylist}/>} 
  </div></main>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-xs font-bold uppercase tracking-[.1em] text-neutral-500 dark:text-neutral-400">{label}<div className="mt-2 normal-case tracking-normal text-inherit">{children}</div></label>}
function Input(props:any){return <input {...props} className="admin-input dark:text-neutral-100"/>}
function Textarea(props:any){return <textarea {...props} className="admin-input min-h-28 dark:text-neutral-100"/>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="border-t border-black/10 pt-5 dark:border-white/10"><p className="editorial-kicker">{title}</p><div className="mt-5 grid gap-5 sm:grid-cols-2">{children}</div></section>}
function Editor({value,setValue,onSave,onCancel,onUpload,saving,message,isArtist,isPlaylist}:{value:Row;setValue:any;onSave:()=>void;onCancel:()=>void;onUpload:(file:File)=>void;saving:boolean;message:string;isArtist:boolean;isPlaylist:boolean}){
  const set=(key:string,val:any)=>setValue((current:Row)=>({...current,[key]:val}));const arr=(key:string)=>Array.isArray(value[key])?value[key].join(", "):"";const tracks=Array.isArray(value.tracks)?value.tracks:[];
  function setTrack(index:number,key:string,val:any){set("tracks",tracks.map((track:Row,i:number)=>i===index?{...track,[key]:val}:track));}
  function setTrackLink(index:number,key:string,val:string){setTrack(index,"links",{...(tracks[index]?.links||{}),[key]:val});}
  function addTrack(){set("tracks",[...tracks,{title:"",artist:"",album:"",note:"",links:{spotify:"",appleMusic:"",amazonMusic:"",youtube:""}}]);}
  function moveTrack(index:number,direction:number){const next=index+direction;if(next<0||next>=tracks.length)return;const copy=[...tracks];[copy[index],copy[next]]=[copy[next],copy[index]];set("tracks",copy);}
  function removeTrack(index:number){set("tracks",tracks.filter((_:Row,i:number)=>i!==index));}
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/60 p-3 sm:p-6"><div className="mx-auto my-4 max-w-5xl bg-white shadow-2xl dark:bg-[#111114]">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-black/10 bg-white/95 px-5 py-4 backdrop-blur dark:border-white/10 dark:bg-[#111114]/95 sm:px-7"><div><p className="editorial-kicker">Editorial entry</p><h2 className="mt-1 font-display text-xl font-black uppercase">{value.id?"Edit":"Create"} {isArtist?"artist spotlight":isPlaylist?"playlist":"content"}</h2></div><button onClick={onCancel} aria-label="Close editor" className="h-9 w-9 border border-black/10 text-lg dark:border-white/15">×</button></div>
    <div className="space-y-9 p-5 sm:p-7">
      <Section title="Basic information"><Field label="Title"><Input value={value.title} onChange={(e:any)=>set("title",e.target.value)}/></Field><Field label="Slug"><Input value={value.slug} onChange={(e:any)=>set("slug",e.target.value)} placeholder="auto-generated if blank"/></Field><Field label="Category"><Input value={value.category||""} onChange={(e:any)=>set("category",e.target.value)}/></Field><Field label="Author"><Input value={value.author||""} onChange={(e:any)=>set("author",e.target.value)}/></Field><Field label="Publish date"><Input type="datetime-local" value={value.publish_date?new Date(value.publish_date).toISOString().slice(0,16):""} onChange={(e:any)=>set("publish_date",e.target.value?new Date(e.target.value).toISOString():value.publish_date)}/></Field><Field label="Month / issue"><Input value={value.month||""} onChange={(e:any)=>set("month",e.target.value)} placeholder="September 2026"/></Field><Field label="Year"><Input type="number" value={value.year||""} onChange={(e:any)=>set("year",e.target.value?Number(e.target.value):null)}/></Field><Field label="Short description"><Textarea value={value.excerpt||""} onChange={(e:any)=>set("excerpt",e.target.value)}/></Field></Section>
      <Section title="Editorial"><Field label="Tags"><Input value={arr("tags")} onChange={(e:any)=>set("tags",e.target.value.split(",").map((x:string)=>x.trim()).filter(Boolean))}/></Field><Field label="Genres"><Input value={arr("genre")} onChange={(e:any)=>set("genre",e.target.value.split(",").map((x:string)=>x.trim()).filter(Boolean))}/></Field><div className="sm:col-span-2"><Field label="Article / editorial content · Markdown supported"><Textarea className="min-h-[360px]" value={value.body||""} onChange={(e:any)=>set("body",e.target.value)}/></Field></div></Section>
      <Section title="Media"><div className="sm:col-span-2"><Field label="Cover image"><div className="flex gap-2"><Input value={value.cover_image||""} onChange={(e:any)=>set("cover_image",e.target.value)} placeholder="/images/example.jpg"/><label className="inline-flex shrink-0 cursor-pointer items-center gap-2 border border-black/10 px-4 py-2 text-[10px] font-bold uppercase tracking-wider dark:border-white/15"><ImagePlus size={14}/><input type="file" accept="image/*" className="hidden" onChange={(e:any)=>e.target.files?.[0]&&onUpload(e.target.files[0])}/>Upload</label></div></Field></div><div className="sm:col-span-2"><Field label="Cover image alt text"><Input value={value.cover_image_alt||""} onChange={(e:any)=>set("cover_image_alt",e.target.value)}/></Field></div>{isArtist&&<><Field label="Artist image URL"><Input value={value.artist_image||""} onChange={(e:any)=>set("artist_image",e.target.value)}/></Field><Field label="Artist name"><Input value={value.artist_name||""} onChange={(e:any)=>set("artist_name",e.target.value)}/></Field></>}</Section>
      {isArtist&&<Section title="Artist information"><Field label="Location"><Input value={value.location||""} onChange={(e:any)=>set("location",e.target.value)}/></Field><Field label="Country"><Input value={value.country||""} onChange={(e:any)=>set("country",e.target.value)}/></Field><Field label="Artist website"><Input value={value.artist_links?.website||""} onChange={(e:any)=>set("artist_links",{...(value.artist_links||{}),website:e.target.value})}/></Field><Field label="Instagram / profile"><Input value={value.artist_links?.instagram||""} onChange={(e:any)=>set("artist_links",{...(value.artist_links||{}),instagram:e.target.value})}/></Field></Section>}
      {isPlaylist&&<section className="border-t border-black/10 pt-5 dark:border-white/10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="editorial-kicker">Music</p><h3 className="mt-1 font-display text-2xl font-black uppercase">Track manager</h3><p className="mt-1 text-xs text-neutral-500">Add, edit and reorder songs. Amazon Music lives here with the other streaming links.</p></div><button type="button" onClick={addTrack} className="bg-black px-4 py-2 text-[10px] font-bold uppercase tracking-[.12em] text-white dark:bg-white dark:text-black">+ Add track</button></div><div className="mt-5 space-y-3">{tracks.map((track:Row,index:number)=><div key={index} className="border border-black/10 p-4 dark:border-white/10"><div className="flex items-start gap-3"><span className="font-mono text-xs text-neutral-400">{String(index+1).padStart(2,"0")}</span><div className="grid flex-1 gap-3 sm:grid-cols-2"><Input value={track.title||""} placeholder="Song title" onChange={(e:any)=>setTrack(index,"title",e.target.value)}/><Input value={track.artist||""} placeholder="Artist" onChange={(e:any)=>setTrack(index,"artist",e.target.value)}/><Input value={track.album||""} placeholder="Album" onChange={(e:any)=>setTrack(index,"album",e.target.value)}/><Input value={track.note||""} placeholder="Editorial note" onChange={(e:any)=>setTrack(index,"note",e.target.value)}/><Input value={track.links?.spotify||""} placeholder="Spotify URL" onChange={(e:any)=>setTrackLink(index,"spotify",e.target.value)}/><Input value={track.links?.appleMusic||""} placeholder="Apple Music URL" onChange={(e:any)=>setTrackLink(index,"appleMusic",e.target.value)}/><Input value={track.links?.amazonMusic||""} placeholder="Amazon Music URL" onChange={(e:any)=>setTrackLink(index,"amazonMusic",e.target.value)}/><Input value={track.links?.youtube||""} placeholder="YouTube URL" onChange={(e:any)=>setTrackLink(index,"youtube",e.target.value)}/></div><div className="flex shrink-0 flex-col gap-1"><button type="button" onClick={()=>moveTrack(index,-1)} aria-label="Move track up" className="border p-2 text-neutral-500 hover:text-accent"><ArrowUp size={13}/></button><button type="button" onClick={()=>moveTrack(index,1)} aria-label="Move track down" className="border p-2 text-neutral-500 hover:text-accent"><ArrowDown size={13}/></button><button type="button" onClick={()=>removeTrack(index)} aria-label="Remove track" className="border border-red-500/30 p-2 text-red-600"><Trash2 size={13}/></button></div></div></div>)}{!tracks.length&&<p className="border border-dashed border-black/10 p-8 text-center text-xs text-neutral-500 dark:border-white/10">No tracks yet.</p>}</div></section>}
      <Section title="Publishing"><div className="sm:col-span-2 flex flex-wrap gap-6 border border-black/10 p-4 dark:border-white/10"><label className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider"><input type="checkbox" checked={!!value.featured} onChange={(e)=>set("featured",e.target.checked)}/> Featured</label><label className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider"><input type="checkbox" checked={!!value.draft} onChange={(e)=>set("draft",e.target.checked)}/> Draft</label></div></Section>
      <Section title="SEO"><Field label="SEO title"><Input value={value.seo_title||""} onChange={(e:any)=>set("seo_title",e.target.value)}/></Field><Field label="SEO description"><Textarea value={value.seo_description||""} onChange={(e:any)=>set("seo_description",e.target.value)}/></Field><Field label="SEO image"><Input value={value.seo_image||""} onChange={(e:any)=>set("seo_image",e.target.value)}/></Field><Field label="Canonical URL"><Input value={value.canonical_url||""} onChange={(e:any)=>set("canonical_url",e.target.value)}/></Field></Section>
    </div>
    <div className="sticky bottom-0 flex flex-wrap items-center justify-between gap-4 border-t border-black/10 bg-white/95 px-5 py-4 backdrop-blur dark:border-white/10 dark:bg-[#111114]/95 sm:px-7"><span className="text-sm text-neutral-500">{message}</span><div className="flex gap-2"><button onClick={onCancel} className="border border-black/10 px-5 py-3 text-xs font-bold uppercase tracking-wider dark:border-white/15">Cancel</button><button disabled={saving} onClick={onSave} className="bg-accent px-5 py-3 text-xs font-bold uppercase tracking-wider text-white disabled:opacity-50">{saving?"Saving…":"Save entry"}</button></div></div>
  </div></div>;
}
